#index:
#    path: /
#    controller: App\Controller\DefaultController::index
main_page:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'main.html.twig'